### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by HeroRebor** [Torom/BotLi#10]
So I want to  deploy my repi with heroku but it's not connecting can u write thr command line how to upload with git in heroku branch plz

**Comment by Torom** [comment]
This is a Heroku issue, here is the corresponding Heroku notice: [https://status.heroku.com/incidents/2413](https://status.heroku.com/incidents/2413)

There are other ways to deploy to Heroku, but this requires the Heroku CLI. Instructions for this can be found here: [https://devcenter.heroku.com/articles/git](https://devcenter.heroku.com/articles/git)

**Comment by Torom** [comment]
With 88336a5 I changed the way BotLi is deployed on Heroku from Procfile to Docker. From now on, the Heroku CLI is always required. But this also fixes the current problem that Heroku can't connect to GitHub.

There is no longer a `heroku` branch, everything needed to run BotLi on Heroku is in the `main` branch.

[Here](https://github.com/Torom/BotLi#how-to-deploy-to-heroku) in an explanation of how to start BotLi now on Heroku.

**Comment by Torom** [comment]
I have again changed the way how BotLi is deployed to Heroku. I now use a [GitHub Action](https://github.com/AkhileshNS/heroku-deploy). The Heroku CLI is no longer needed and it is again possible to push every change automatically to Heroku.

The instructions [here](https://github.com/Torom/BotLi#how-to-deploy-to-heroku) have been updated.

**Comment by SriMethan** [comment]
@Torom as this issue is fixed, this issue should be unpined

**Comment by Torom** [comment]
The problem is fixed, therefore the issue is closed.

I left it pinned so that new users can find the solution to the still existing Heroku problem.

**Comment by FatFritz2** [comment]
I am having an issue again...

=== Fetching app code
=!= Your app does not include a heroku.yml build manifest. To deploy your app, either create a heroku.yml: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml
Or switch back to buildpack-based deploys: https://devcenter.heroku.com/articles/container-registry-and-runtime#changing-deployment-method

**Comment by Torom** [comment]
Where do you see this error? Everything looks fine in your repository during [deployment](https://github.com/FatFritz2/BotLi/runs/7109512105).

**Comment by FatFritz2** [comment]
I see it in dashboard.heroku.com

**Comment by Torom** [comment]
I don't know, I don't use Heroku. Maybe you did something wrong, maybe Heroku changed something again.

**Comment by SriMethan** [comment]
Yes I have noticed this during my deployment too... , and I fixed that error by deploying it with a heroku.yml file
