### ISSUE TITLE
How do I set up a bot with Lc0

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#101]
I want to set up a bot with Lc0, running only on GPU no cpu... How do you use the UCI options for this? I want to allocate 8GB of RAM, full GPU, and also set up the default network file... I am on Windows 10. Also, is there any way to also use the Lc0 Training client while doing this? 

Any help would be appreciated

**Comment by Torom** [comment]
Sorry, but these are not BotLi questions. I use Leela with BotLi without any problems.

**Comment by EmptikBest** [comment]
Ok, but what should I put in the UCI options in BotLi?

**Comment by EmptikBest** [comment]
I don't want to use the CPU... I saw that Lc0 can run on GPU alone, that is what I want to configure in the UCI options of BotLi

**Comment by Torom** [comment]
You put the UCI options into the `uci_options` which should be set in the engine.

**Comment by EmptikBest** [comment]
Thanks
