### ISSUE TITLE
Rate limit?

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#103]
My bot had matchmaking off, it played a game 8 minutes ago... I typed `create 500 emptikvariantsbot 60 0 true standard` and it told me the following (copied cmd text):
```
create 500 emptikvariantsbot 60 0 true standard
Challenges for 500 game pairs against emptikvariantsbot added to the queue.
Challenging emptikvariantsbot ...
Challenge against emptikvariantsbot failed due to Lichess rate limit.
Challenge queue cleared due to rate limiting.
```

How is it rate limited? It didn't even challenge for like 2 hours before this.. Only accepted incoming challenges and even the last incoming challenge was 8 minutes ago...

**Comment by Torom** [comment]
Lichess has a rate limit of 200 challenges against bots per day, one challenge to a human counts as 5 challenges. So you can be rate limited.

**Comment by EmptikBest** [comment]
Ok, thank you!

By the way, sorry @Torom for not knowing how to use the code blocks before... I just used to use the code option at the top and then copy paste the text
