### ISSUE TITLE
Correspondence Games

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#105]
**Is your feature request related to a problem? Please describe.**
Not really, sometimes it's just annoying the fact I can't use this for correspondence.

**Describe the solution you'd like**
I would like it so BotLi supports correspondence and have a different 'concurrency' section for correspondence games.

**Describe alternatives you've considered**
Lichess-bot maybe?

**Additional context**
None

**Comment by Torom** [comment]
I looked into it and I don't know if it's worth the effort. I find correspondence games with bots pretty pointless and if you look at Lichess they are almost never played.

I'm not around for a week, I might look at it again afterwards. If more people are interested in the feature, they can leave a +1 here.

bddfc72 is the first step to make correspondence games possible with some nice side effects.

**Comment by EmptikBest** [comment]
Ok, I really hope you do it since I'm having to use lichess-bot for my correspondence games

**Comment by FatFritz2** [comment]
I see you have created a bot called `https://lichess.org/@/EmptikCorrespondence` you can just force it to play correspondance only with `https://github.com/lichess-bot-devs/lichess-bot`

**Comment by EmptikBest** [comment]
@FatFritz2, yes, I have created my bot using lichess-bot, but lichess-bot doesn't have as many options as this does. That is why I switched from lichess-bot to BotLi.

**Comment by FatFritz2** [comment]
@EmptikBest, @Torom doesn't (really) want to add correspondence game to his bot. I guess its not the right time now due to the demand for that option is really low

**Comment by M-DinhHoangViet** [comment]
@FatFritz2 no, now me and many people are in need

**Comment by EmptikBest** [comment]
Agree with @M-DinhHoangViet.

**Comment by EmptikBest** [comment]
Well, if it is not in progress, I may as well close this issue
