### ISSUE TITLE
Offer draw according to EGTB

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#110]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like it so there is a option to ONLY accept/offer draw if the EGTB returns the value as draw/loss.

**Describe alternatives you've considered**
Lichess-bot has this feature I think, but in that way you have a all or nothing package.

**Additional context**
No.

**Comment by Torom** [comment]
You can already do that. Just set the `min_game_length` or the `consecutive_moves` to an unrealistically high value like 300. Neither syzygy nor gaviota nor the online egtb respect these values.

**Comment by EmptikBest** [comment]
But will that offer/accept draw?

**Comment by Torom** [comment]
Yes. `min_game_length` and `consecutive_moves` are only considered for draw offers based on the engine eval.
