### ISSUE TITLE
Any difference between BotLi nogit and BotLi 20230629-8bbc829, 20230623-5007333...

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#112]
Hi @Torom 

Currently, I am using BotLi nogit but I am wondering if other people use BotLi 20230623-5007333 or 20230629-8bbc829...
So is nogit or those other versions better ?
Can you explain a bit clear since I am having no experience with this.
So if that 20230629 is better, how do I get that ?
Thanks

**Comment by Torom** [comment]
There is not necessarily a difference between the versions, I'll explain:

The versioning of BotLi works with git. The versions you name are composed of the date of the last commit and the commit hash. The version `nogit` only means that no git was found on the system. Therefore BotLi cannot determine the last commit. If you install git on your system the version will automatically become the correct version consisting of date and hash.

**Comment by FatFritz2** [comment]
Oh ok thanks for explaining
