### ISSUE TITLE
How to use BotLi in Ubuntu 23.04 ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#115]
Hey @Torom 
I've recently installed Ubuntu to my new computer.
I have got the python with latest version and I have no idea how to use BotLi in Linux-based OS (eg: Ubuntu...) 
Can you guide me ? Futhermore you should provide steps to use BotLi with Linux-based OSes in the ReadMe file
Thanks

**Comment by EmptikBest** [comment]
Most of the readme.md IS for linux, for example `git clone` is linux and `/home/Books/Goi.bin` IS a linux path 🤦

**Comment by Torom** [comment]
> Can you guide me ?

No.

> Futhermore you should provide steps to use BotLi with Linux-based OSes in the ReadMe file

As EmptikBest said, the readme is written for Linux.

**Comment by EmptikBest** [comment]
@FatFritz2 this is your 45th issue, I have looked through almost all your other issues too. I really think you should provide more information about what is happening and give info about your OS/Python version as written in the create issue bug report template

**Comment by FatFritz2** [comment]
Oh Finally I've got it using .venv when trying to install the requiremnets
Thanks

**Comment by EmptikBest** [comment]
@FatFritz2 it should work without venv with --break-system-packages too

**Comment by FatFritz2** [comment]
@Torom 
The python 3.11.2 is not working anymore and it keeps showing this error when I try to install all dependencies:

![image](https://github.com/Torom/BotLi/assets/107122824/751e5c1b-c4a7-43d1-9114-a1b162a4012d)

Anyways how to resolve this

**Comment by Torom** [comment]
The first (and actually only) requirement to use BotLi is a working python >= 3.10. Since you already fail at this (which I don't understand, RaspFish runs on Ubuntu 23.04 without further ado) I can't / don't want to help you.

But I'm sure the internet is full of help for your problem. Maybe you just need to google yourself instead of always asking others to fix your problems.

**Comment by EmptikBest** [comment]
@FatFritz2 I get the same error, either use virtualenv (not what I did) or run `python3 -m pip install -r requirements.txt --break-system-packages`, it didnt break anything for me, and worked

**Comment by FatFritz2** [comment]
> @FatFritz2 I get the same error, either use virtualenv (not what I did) or run `python3 -m pip install -r requirements.txt --break-system-packages`, it didnt break anything for me, and worked

Thanks @EmptikBest  you saved me
