### ISSUE TITLE
NPS

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#116]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If it's possible, I'd like so there is an option to only search for a specific amount of nodes based on something you've written in the config.yml (I know this is possible via go_commands), for EACH opponent. Like there should be a section called Search: or something in which for some opponents you can write their average NPS and if playing against them you can set a multiplier for that so the bot only searches for those many nodes (based on the time the opponent spent thinking, NPS*Seconds = nodes, also to take this further if possible there can be another option that takes in consider ponder). It would help the bot save time.

**Describe alternatives you've considered**
No alternatives yet, just came into my mind.

**Additional context**
There could be a section in the config.yml like the following:
```
Search:                   # Search for these many nodes per opponent, valid options for ponder are true/false. Format: [USERNAME] [NPS] [PONDER]
   - emptikbot 30000000 true
   - emptikvariantsbot 15000000 false
```
Examples could be different and maybe it could be commented out in the original config.yml, thanks in advance.

EDIT: Also it could search less nodes if the bot doesnt have enough time on the clock to search the specified nodes

**Comment by Torom** [comment]
> I know this is possible via go_commands

BotLi does not have such a configuration.

The rest is theoretically possible, but definitely outside of what I will support with BotLi.
