### ISSUE TITLE
BotLi error on mac M1 Ventura

### ISSUE THREAD

**Issue by microsmeta** [Torom/BotLi#117]
Trying to use your script with Python 3.11.4 (I have same config.yml configured and working fine on Windows 10) , I get this error:

Traceback (most recent call last):
  File "/Users/alessandromorales/BotLi-main/user_interface.py", line 7, in <module>
    from api import API
  File "/Users/alessandromorales/BotLi-main/api.py", line 9, in <module>
    from botli_dataclasses import API_Challenge_Reponse, Challenge_Request
  File "/Users/alessandromorales/BotLi-main/botli_dataclasses.py", line 8, in <module>
    class API_Challenge_Reponse:
  File "/Users/alessandromorales/BotLi-main/botli_dataclasses.py", line 9, in API_Challenge_Reponse
    challenge_id: Challenge_ID | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Kind regards, Alex

**Comment by microsmeta** [comment]
You are right :)

installed using brew and there must be an issue... downloading 3.11.4.1,
installed but python ---version returns always 3.9.6 ...I must solve this
conflict uninstalling all. Is a Python issue, not BotLi related. Thanks for
your support!

*brew.sh/api/formula.jws.json <http://brew.sh/api/formula.jws.json>*

#=#=#


==> *Fetching ***@***.****

==> *Downloading
https://ghcr.io/v2/homebrew/core/python-gdbm/3.11/manifests/3.11
<https://ghcr.io/v2/homebrew/core/python-gdbm/3.11/manifests/3.11>*

#########################################################################
100.0%

==> *Downloading
https://ghcr.io/v2/homebrew/core/python-gdbm/3.11/blobs/sha256:c
<https://ghcr.io/v2/homebrew/core/python-gdbm/3.11/blobs/sha256:c>*

#########################################################################
100.0%

==> *Pouring ***@***.***_ventura.bottle.tar.gz*

🍺  ***@***.***/3.11.4: 5 files, 101.3KB

==> *Running `brew cleanup ***@***.***`...*

Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.

Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

***@***.*** ~ % python --version

Python 3.9.6


Il giorno mar 11 lug 2023 alle ore 15:31 Torom ***@***.***>
ha scritto:

**Comment by Torom** [comment]
I'm going to close this as it's not a BotLi error. I'm sure there is plenty of help online on how to install any version of Python on Mac.

**Comment by microsmeta** [comment]
Thank you not only for this, but for your contribuite to the whole chess
community 🙂

Alex

Il gio 13 lug 2023, 23:59 Torom ***@***.***> ha scritto:
