### ISSUE TITLE
CTG Book Support

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#119]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I'd like so CTG book support could be added into BotLi if possible, also I'm sorry if it feels like I am spamming enhancement requests.

**Describe alternatives you've considered**
Not any so far.

**Additional context**
Maybe a section in the config.yml:
```
ctg:
   - book1.ctg
   - book2.ctg
```
Or something like that

**Comment by Torom** [comment]
BotLi uses the amazing python-chess library, also to read polyglot books. But it does not support CTG books at the moment, but it was a topic there before see niklasf/python-chess#46 (8 years ago).

I don't plan to implement a CTG reader myself, as the format seems quite complex and consists of several files per book. The linked CTG specification is also offline by now. If python-chess supports CTG books in the future, I will probably make use of it in BotLi.
