### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#120]
Hello, I was wondering the priority of opening books in BotLi. For example you have 2 opening books, one with 1.e4 weight as 75, and the other with 1.d4 weight as 75... Which one will be prioritized first? Is it like vertically descending, the first book you mention gets priority, or what? Thanks in advance

**Comment by EmptikBest** [comment]
Okay, I think that it should be sequential only, as I have around 50 books, and now as you have confirmed I can sort them in priority, and with that, tune them too... Thanks.. Also, just another question, if all the weights in the first book are 0, then is a random move selected from it or is the next book used, which has non-zero weights?

**Comment by Torom** [comment]
I have to correct myself. A move from the first book is played if one of the moves has a non-zero weight. Moves with a weight of zero are generally ignored. So if there are only moves with a weight of zero, the next book is checked.

How moves with the same weight are handled depends on which selection you have configured. With `best_move` the move that is first in the book is played. With `weighted_random` surprisingly a weighted random move is played.

**Comment by EmptikBest** [comment]
But if two moves dont have the same weight in a book (ex 1.e4 75 and 1.d4 25) with best move is e4 played even if d4 is first (By first mean like higher in the list of moves when opened with SCID vs PC)

**Comment by Torom** [comment]
What selection are you talking about?

The order of the moves in the book is only considered in the selection 'best_move' if several moves have the highest weight. Then the move that is higher up is played.

**Comment by EmptikBest** [comment]
Oh okay, thanks
