### ISSUE TITLE
Request: Different engines for different TCs

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#131]
**Is your feature request related to a problem? Please describe.**
No problem at all, except that I have found some engines that are better in different TCs then other engines..

**Describe the solution you'd like**
If possible, can there be a option for different engines for different TCs? Sort of like:
```
bullet:  
  dir: "F:/EmptikBot/engines"             # Directory containing the engine.
  name: "stockfish.exe"                      # Binary name of the engine to use.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 500                    # Increase if your bot flags games too often.
    Threads: 28                           # Max CPU threads the engine can use.
    Hash: 8192                            # Max memory (in megabytes) the engine can allocate.
blitz:
  dir: "F:/EmptikBot/engines"             # Directory containing the engine.
  name: "Emptik.exe"                      # Binary name of the engine to use.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 500                    # Increase if your bot flags games too often.
    Threads: 28                           # Max CPU threads the engine can use.
    Hash: 8192                            # Max memory (in megabytes) the engine can allocate.
    Experience Book: true
```

And so on for blitz, rapid, classical....

**Describe alternatives you've considered**
None.

**Additional context**

EDIT:
Maybe same thing is also possible with opening books?

**Comment by Torom** [comment]
> Maybe same thing is also possible with opening books?

You can already do that since 7511ae7.

**Comment by EmptikBest** [comment]
Oh thanks! I didnt know sorry..

Are you going to implement this with engines? It would help me greatly

Thanks

**Comment by M-DinhHoangViet** [comment]
I think the way to do it is similar to the code of Standard chess and Chess Variant right @Torom ? Or is it different?

**Comment by EmptikBest** [comment]
Thanks!
