### ISSUE TITLE
Reformat !eval and !printeval command

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#142]
Hi @Torom 
I want to reformat the !eval and !printeval format from
Old format: `0.05 33/39 Nodes: 6.3 M NPS: 1.5 M MT: 00:04.3 Hash: 4.0 % PV: 53. Rh8 Rc2 54. b7 Nc6 55. Rc8 Ra2+ 56. Kb5 Nxe5`
To this lichess-bot format:  `Source: Engine, Evaluation: -0.08, Winrate: 49.8%, Depth: 20, Nodes: 669.5K, Speed: 1.0Mnps, Pv: 26...Bxc5 27. Be1 Nb4 28. Bxb4 Rxb4 29. a5`
In my opinion, I think the lichess-bot format is clearly better for me since it supports UCI_WDL feature, clear expressions and If you reformat it i really hope you add the hash info right after the Speed and I think you can put the Move time to the very last just before the PV 

Thats my idea
Thanks

**Comment by Torom** [comment]
I am leaving the issue open to allow others to comment.

I am strongly against it right now:
- It needs much more space than the current format.
- It even contains less information than the current format.
- I think also the current format is to understand.
- Winrate' is the completely wrong name for the wdl output (but I can't think of a better one). With an eval of 0.00 you certainly don't have a win rate of 50%. What they mean is rather "expected score" or something like that.

**Comment by FatFritz2** [comment]
If you dont want to do it, I suggest you adjust the NPS: ...M to Speed: ...Mnps format

**Comment by EmptikBest** [comment]
I personally think that the current BotLi eval is much better than lichess-bot..

If you want all these features from lichess-bot added, then just go use lichess-bot??

@Torom, correct me if I'm right, but I see 49 of the 104 issues are opened by @FatFritz2..

@FatFritz2, if you want all these features so badly, then instead go to lichess-bot and ask them to add BotLi features instead..

In fact, in lichess-bot, you already requested multiple features from BotLi:
 - Bullet with increment only
 - !printeval

**Comment by FatFritz2** [comment]
I've already asked them about that  features https://github.com/lichess-bot-devs/lichess-bot/issues/770
and https://github.com/lichess-bot-devs/lichess-bot/issues/714

**Comment by EmptikBest** [comment]
Didnt I say just that in the post??

**Comment by Torom** [comment]
Let's focus on the issue here. The [Discord server](https://discord.gg/6aS945KMFD) is better suited for such discussions.

**Comment by EmptikBest** [comment]
Yeah, I think that the current eval is just fine, and even better than lichess-bot eval.. and I think that many people will agree with me...
Also, just my thought, we can improve one tiny detail, if it doesnt take too much space, and that we add `Evaluation: <score>` rather than `<score>` at the beginning..

**Comment by Torom** [comment]
But the `!eval` output is already: `Evaluation: 63. Kg3 +0.09 45/37 Nodes: 8.5 M NPS: 6.9 M MT: 00:01.2 Hash: 3.7 % TB: 12.6 k PV: 63... Ra1 64. Rb2 Ra6 65. Rb5 Ra2 66. Kh3 Ra6`

I guess you mean that `Evaluation:` comes before the score and not at the beginning. That makes sense. But the advantage at the moment is that BotLi simply saves the last message that was printed to the user, only the PV may be appended. And for the user `Engine:` must be at the beginning. But let's see, I will probably generate a private and a public part of the message soon. Then also the book name or similar will not be sent into the chat.

**Comment by EmptikBest** [comment]
> But the `!eval` output is already: `Evaluation: 63. Kg3 +0.09 45/37 Nodes: 8.5 M NPS: 6.9 M MT: 00:01.2 Hash: 3.7 % TB: 12.6 k PV: 63... Ra1 64. Rb2 Ra6 65. Rb5 Ra2 66. Kh3 Ra6`
> 
> I guess you mean that `Evaluation:` comes before the score and not at the beginning. That makes sense. But the advantage at the moment is that BotLi simply saves the last message that was printed to the user, only the PV may be appended. And for the user `Engine:` must be at the beginning. But let's see, I will probably generate a private and a public part of the message soon. Then also the book name or similar will not be sent into the chat.

I'm sorry, I didnt exactly remember properly..

Yes you are correct, but in @FatFritz2's post it is not written Evaluation:..

I dont think BotLi eval messages needs changes

**Comment by IbaiBuR** [comment]
In my opinion there is no need to change the eval/printeval output either, it is already fine as it is. now

As Torom said, if you like the lichess-bot output either you try to implement it yourself in BotLi for your private use or just use lichess-bot!

**Comment by FatFritz2** [comment]
I guess you guys're right 
I will close the issue right now
