### ISSUE TITLE
NNUE using

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#18]
Hey author,
Please tell me how to use NNUE on the bot please
Thank you

**Comment by Torom** [comment]
You would have to be more specific what you want please. Every Stockfish since version 12 uses NNUE.

**Comment by FatFritz2** [comment]
I want to know how to use a NNUE file to make my engine stronger

**Comment by Torom** [comment]
All engines I know implement the NNUE in the binary. So there are no
further steps necessary.

If this is not the case, you can probably control it via the UCI options.
These can be set in the config.yml in the uci_options section.

**Comment by FatFritz2** [comment]
I mean is there anyway to enter a link with the NNUE file in config.yml or any other files ?

**Comment by FatFritz2** [comment]
Stockfish 200622_modern.exe + NNUE file

**Comment by Torom** [comment]
You would have to be more specific what you want please. Every Stockfish since version 12 uses NNUE.

**Comment by Torom** [comment]
If you have the binary from abrok or somewhere else, the NNUE is already implemented. You don't have to do anything to use NNUE.

**Comment by FatFritz2** [comment]
I rlly want to change the NNUE to make it stronger

**Comment by Torom** [comment]
There is no stronger network than the official one. But anyway.

[Here](https://github.com/official-stockfish/Stockfish#evalfile) is how to set the NNUE to use. Just add such a line to the `uci_options` section in config.yml.

```yaml
EvalFile: "nn-3c0aa92af1da.nnue"
```

For example. Of course you have to make sure that the engine can find the NNUE.

**Comment by FatFritz2** [comment]
But why my engine got an error i added the nnue in the Path

**Comment by FatFritz2** [comment]
uh ok

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/176207202-ee096eee-e02a-4646-bdfe-16d4b6aee627.png)
thats what happened when i tried to start the bot :(

**Comment by Torom** [comment]
It would be best if you test it first without BotLi. So directly with the
engine. If that works, BotLi should have no problems.

There can be many reasons why it does not work. Maybe the net is not the
right architecture.

**Comment by FatFritz2** [comment]
My NET is v4.0 i think...
I got the NNUE file from fairy-stockfish.github.io
The NNUE worked on f-s 14 outside of BotLi of course

**Comment by Torom** [comment]
That's the problem, NNUE from fairy-stockfish are not compatible with Stockfish. Either you use fairy-stockfish or you use Stockfish compatible nets.

**Comment by FatFritz2** [comment]
wow ok thanks

**Comment by Torom** [comment]
If you have the binary from abrok or somewhere else, the NNUE is already
implemented. You don't have to do anything to use NNUE.
