### ISSUE TITLE
Time control

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#26]
Hey, how can I adjust my bot's accepted time control? I mean I have to adjust the minutes per side to 1 minute

**Comment by Torom** [comment]
[Here](https://github.com/Torom/BotLi/blob/5a58159f2878728fbd442ef54d95b21b581bc2fd/config.yml.default#L73) you can set the time controls that should be accepted.

And in [these lines](https://github.com/Torom/BotLi/blob/5a58159f2878728fbd442ef54d95b21b581bc2fd/config.yml.default#L58-L61) you can set exactly how much initial time and how much increment the challenges are allowed to have. The values are obviously in seconds.

That wasn't really hard to find, was it?

**Comment by FatFritz2** [comment]
Cool
