### ISSUE TITLE
How to setup LC0 TO botli and Botli Heroku??

### ISSUE THREAD

**Issue by RoboTicCoders** [Torom/BotLi#27]
I really want to know how to set up lc0 to BotLi.Is there a way that i can setup ??? i want to know whether there is a possibility and the lc0's supported commands to botli as well

**Comment by Torom** [comment]
You closed the issue again, so you don't expect an answer anymore?

However, Lc0 should work with BotLi, any UCI engine should work. I have never tested it, but it should not be a problem.

Lc0 cannot be used on Heroku regardless of BotLi or any other bot.

**Comment by RoboTicCoders** [comment]
sorry my bad ..How
