### ISSUE TITLE
Strength

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#30]
I want to know how to increase my bot's strength and why it times out quite often while playing with AI level 8 ?

**Comment by Torom** [comment]
There is no secret option to make the bot stronger. In my opinion, the strength is a combination of hardware and opening book. If you want a stronger bot, run it on stronger hardware or with a better opening book.

What kind of time control were the lost games? I don't use Heroku myself and I don't notice any lost games on time. Maybe your configuration does not fit Heroku? I don't recommend to play bullet games without increment.
