### ISSUE TITLE
challenge error

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#36]
Idk how to fix this: 
challenge RaspFish [60] [1] [White] [RATED] [standrard]
invalid literal for int() with base 10: '[10]'

**Comment by Torom** [comment]
Drop the `[]`. They only say that this option is optional.

`challenge RaspFish 60 1 white` means exactly the same. Rated is the default and standard chess is the default variant.

**Comment by FatFritz2** [comment]
ok lemme see thanks
