### ISSUE TITLE
Add NNUE Eval for fsf

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#39]
How do I add NNUE files in Dockerfile to make fairy stockfish stronger because its making too much blunders
![image](https://user-images.githubusercontent.com/107122824/183113465-f77ca591-f741-4f05-8cd0-99dc20951fb6.png)
 And can it uses more than 1 eval file at once?
Thank

**Comment by Torom** [comment]
Download the NNUEs from here: https://fairy-stockfish.github.io/nnue/#current-best-nnue-networks, put them next to the engine and adjust the uci_options of the variant engine accordingly: https://github.com/ianfab/Fairy-Stockfish/wiki/Settings#evalfile

**Comment by FatFritz2** [comment]
Ok let me see what would happen

**Comment by FatFritz2** [comment]
Does this work on Heroku i mean ?

**Comment by Torom** [comment]
I guess so, why don't you just give it a try?

**Comment by FatFritz2** [comment]
Uh ok let me try one and if works i will report to u

**Comment by FatFritz2** [comment]
Uh where should I place those NNUE files: 
Directly on BotLi or in engines folder???

**Comment by Torom** [comment]
> Download the NNUEs from here: https://fairy-stockfish.github.io/nnue/#current-best-nnue-networks, **put them next to the engine** and adjust the uci_options of the variant engine accordingly: https://github.com/ianfab/Fairy-Stockfish/wiki/Settings#evalfile

So in the engines folder.

**Comment by FatFritz2** [comment]
Oh thanks

**Comment by FatFritz2** [comment]
What I can't add those files. Its way too heavy

**Comment by Torom** [comment]
I originally meant that you download the NNUEs in the Dockerfile. But you can also upload them to your repo.

**Comment by FatFritz2** [comment]
I can't upload it . Cuz its way too Heavy. Github does not allow me to upload all those files :(

**Comment by Torom** [comment]
Add this to your Dockerfile:

```Dockerfile
RUN wget "https://drive.google.com/u/0/uc?id=1r5o5jboZRqND8picxuAbA0VXXMJM1HuS&export=download" -O engines/3check-313cc226a173.nnue

RUN wget "https://drive.google.com/u/0/uc?id=14CYA7qV1Jsh5g-lpg46-tz9Whp8zN0aI&export=download" -O engines/atomic-e801e22d2c32.nnue

RUN wget "https://drive.google.com/u/0/uc?id=168vawXrj2fEeRSLuWaL2pB7GXgQelE-c&export=download" -O engines/crazyhouse-be2e41920378.nnue

RUN wget "https://drive.google.com/u/0/uc?id=16BQztGqFIS1n_dYtmdfFVE2EexF-KagX&export=download" -O engines/horde-28173ddccabe.nnue

RUN wget "https://drive.google.com/u/0/uc?id=1x25r_1PgB5XqttkfR494M4rseiIm0BAV&export=download" -O engines/kingofthehill-978b86d0e6a4.nnue

RUN wget "https://drive.google.com/u/0/uc?id=1Tiq8FqSu7eiekE2iaWQzSdJPg-mhvLzJ&export=download" -O engines/racingkings-636b95f085e3.nnue
```

And this to your `uci_options` of the variant engine:

```yaml
EvalFile: "3check-313cc226a173.nnue:atomic-e801e22d2c32.nnue:crazyhouse-be2e41920378.nnue:horde-28173ddccabe.nnue:kingofthehill-978b86d0e6a4.nnue:racingkings-636b95f085e3.nnue"
```

**Comment by FatFritz2** [comment]
Thanks A lot

**Comment by FatFritz2** [comment]
OMG YAY IT WORKS THANKS A LOT

**Comment by FatFritz2** [comment]
Btw after adding,Heroku stated those lines:
2022-08-05T17:08:18.050083+00:00 heroku[worker.1]: Process running mem=538M(105.1%)
2022-08-05T17:08:18.051817+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-08-05T17:08:38.162694+00:00 heroku[worker.1]: Process running mem=538M(105.2%)
2022-08-05T17:08:38.164575+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-08-05T17:08:59.517992+00:00 heroku[worker.1]: Process running mem=539M(105.4%)
2022-08-05T17:08:59.526197+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)

**Comment by Torom** [comment]
That is interesting, probably fairy-stockfish loads all NNUEs at once, and that is then too much for Heroku. You can reduce the `Hash` of fairy-stockfish even more, with the few nps it doesn't need much hash, I'm sure 128 are enough too.

**Comment by FatFritz2** [comment]
Oh let me see then

**Comment by FatFritz2** [comment]
Do I need to use Use NNUE: true function?

**Comment by Torom** [comment]
No, `True` is the default.

**Comment by FatFritz2** [comment]
Ah ok I got it now thanks

**Comment by FatFritz2** [comment]
Btw, can you help me figuring nnue files with the stockfish build pls

**Comment by Torom** [comment]
> Btw, can you help me figuring nnue files with the stockfish build pls

No.

**Comment by FatFritz2** [comment]
oh fine anyway thanks for helping me have a good night :D
