### ISSUE TITLE
Stockfish improvement

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#41]
Can you help me how to get NNUE files to make stockfish dev better (standard) and antichess NNUE file for fsf pls

**Comment by Torom** [comment]
No. There are no better NNUEs for stockfish than the default net and there are no NNUEs for antichess for fairy-stockfish.

**Comment by FatFritz2** [comment]
Oh thanks fine

**Comment by Torom** [comment]
Since yesterday there is a NNUE for antichess. I have updated my post [here](https://github.com/Torom/BotLi/issues/39#issuecomment-1206661025).
