### ISSUE TITLE
column tweak

### ISSUE THREAD

**Issue by bknox83** [Torom/BotLi#44]
It looks like if move time is over 1000 seconds that the columns for hash and tablebase hits become misaligned.
<img width="632" alt="botli" src="https://user-images.githubusercontent.com/64992190/185155917-6ca7bbe1-9290-4e11-b98b-961dfbe4792d.png">

**Comment by Torom** [comment]
Yes I was aware of that, however I thought that no one would ever take more than 16 minutes for a move. :D
Which time control was that?

**Comment by bknox83** [comment]
looks like it was from a challenge I received today of 30+180... - https://lichess.org/tgr9pUTH3UJX

**Comment by Torom** [comment]
I would say that this occurs so rarely that it is not worth leaving space for another character. The impact is also not really serious.

**Comment by Torom** [comment]
As you can see in 36a300e I changed my mind and changed the move time format to `00:00.0`. So now it overflows just after 100 minutes, that really shouldn`t happen. :D
