### ISSUE TITLE
Hmm problem ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#46]
Hello, I guess there is a problem with matchmaking.py.
My bot does not challenge anyone (on Heroku)
![image](https://user-images.githubusercontent.com/107122824/185776320-4e157e50-b5d6-4337-9500-c071692fcc20.png)
![image](https://user-images.githubusercontent.com/107122824/185776336-56094378-1813-4e1e-9750-3aa4826506f2.png)
doesnt challenges anyone

**Comment by Torom** [comment]
Matchmaking works fine for me. Does the problem still persist?
