### ISSUE TITLE
Future plans for BotLi on a Cloud Server

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#47]
Uh Hi, @Torom 
In 25/Aug/22 when on Heroku web, I saw this:
![image](https://user-images.githubusercontent.com/107122824/186723897-aef49d6a-f878-4536-9adc-59cff833362a.png)
Umm I am wondering if there is another way to use "BotLi" on other cloud servers
Because this is a Long Term plans from Heroku, so I guess you should do something with this repo in order to make it usable on other cloud services.
Best regards,

**Comment by Torom** [comment]
That's interesting, "Heroku Dynos" are the ones we use, right?

I don't use BotLi in the "cloud", anyone can run BotLi on all sorts of cloud providers with a few steps. I will not look for a new free one.

But everyone is welcome to look around and try BotLi on different providers. If minor changes to BotLi are needed, I am willing to make them in the repository. Minor changes mean customizations like the Dockerfile or the GitHub Action for deployment.

Heroku support will be removed at the end of November.

**Comment by FatFritz2** [comment]
Um I think you can make changes to use BotLi directly on Githu.io ?
And I find this page, can you take a look and decide what providers should we use ?
https://github.com/cloudcommunity/Free-Hosting

**Comment by Torom** [comment]
I would say this is the better list.
https://github.com/cloudcommunity/Cloud-Free-Tier-Comparison

**Comment by FatFritz2** [comment]
I guess you can deploy it with google cloud server ?

**Comment by FatFritz2** [comment]
Oh I find this provider 
Railway.app

**Comment by FatFritz2** [comment]
Hey @Torom 
After looking for a while I can't find any cloud hosting sites which suites BotLi
But Heroku say that "For students, we will introduce a new program this end of September"
Yea thats all information I got recently

**Comment by FatFritz2** [comment]
OMG @Torom I found a FREE WEB that can carry BotLi rn
It's doprax.com.
But you must try it out to find where to change in Dockerfile... and other docking, lichess_bot files
Thats all I got for you rn

**Comment by Torom** [comment]
On their [pricing page](https://www.doprax.com/pricing/) they state: `Projects stops running after 10 minutes`

**Comment by FatFritz2** [comment]
ye idk what would happens :C

**Comment by FatFritz2** [comment]
I guess we should use Oracle Cloud always free plan ?

**Comment by Torom** [comment]
Sounds okay to me, have you tested it, is there a way to deploy automatically?

**Comment by FatFritz2** [comment]
> Sounds okay to me, have you tested it, is there a way to deploy automatically?

I can't Sorry :(

**Comment by SriMethan** [comment]
Finally Heroku's Free Plan Ends :D

**Comment by Torom** [comment]
As announced I have removed the explicit Heroku support in 7bf3712. The [heroku branch](https://github.com/Torom/BotLi/tree/heroku) will remain in the last version with heroku support if anyone is interested.

I'll close the issue here, I'm still open to make small adjustments if needed for other cloud providers.

**Comment by FatFritz2** [comment]
I guess we should use Railway.app it's working right now

**Comment by FatFritz2** [comment]
IT COULD HANDLE CHALLENGES HERE: 


______       _   _     _
| ___ \     | | | |   (_)
| |_/ / ___ | |_| |    _
| ___ \/ _ \| __| |   | |
| |_/ / (_) | |_| |___| |
\____/ \___/ \__\_____/_|
Handling challenges ...

**Comment by FatFritz2** [comment]
IT COULD PLAY OMG 👯‍♂️

**Comment by FatFritz2** [comment]
@Torom ITS ACTUALLY WORKING :DDDD

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/206835020-1b2c4b08-b85e-4cf8-98be-8647bc2f86c7.png)

**Comment by FatFritz2** [comment]
it's just soo goood now :D

**Comment by FatFritz2** [comment]
And btw it just worked on your old updates one: Partly revert https://github.com/FatFritz2/BotLi/commit/6fbfb965b81ba79a9f29ab51cd75d24a1d25555b
