### ISSUE TITLE
"!eval" command improvements

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#49]
Hey @Torom I have a few suggestions for the !eval command in BotLi:
+) You should add the Total nodes of the engine (Not the nps I mean all nodes counted. I see other Lichess Bot repos also have this like github.com/ShailChoksi/Lichess-bot)
+) I think the depth is quite hard to understand
Like 19/48 36/4 and so on
So you should use the depth only and no /4 or /36 at the botom
Hope you read and reply to me 
Thanks :D

**Comment by Torom** [comment]
I could think about the total node count. But I don't find ShailChoksi/lichess-bot a good example, because their `!eval` output is very unreadable.

There is no problem with the depth output. 19/48 outputs both the depth and the seldepth. This format is quite common in chess GUIs.
