### ISSUE TITLE
config.yml does not have required section  challenge error

### ISSUE THREAD

**Issue by trial-boy-bots** [Torom/BotLi#5]
help me torom

**Comment by Torom** [comment]
You have to give me more information to help you. Maybe post the `config.yml` you try to use. But __delete__ the token before.

**Comment by trial-boy-bots** [comment]
token: "xxx(token)"    # Lichess OAuth2 Token.
 

 engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing the engine. This can be an absolute path or one relative to lichess-bot/.
  name: "sf.exe"        # Binary name of the engine to use.
  working_dir: ""            # Directory where the chess engine will read and write files. If blank or missing, the current directory is used.
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.                       # Think on opponent's time.
  opening_books:
    enabled: true                      # Activate opening books.
    books:
      white:                              # List of names of books to use as white.
        - "book1.bin"
      black:                              # List of names of books to use as black.
        - "book2.bin"
      standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "book1.bin" 
#     chess960:                           # List of names of books to use for Chess960.
#       - "Chess960Book"
    selection: "weighted_random"          # Move selection is one of "weighted_random", "uniform_random" or "best_move".
  online_moves:
    chessdb:
      enabled: false                      # Activate online moves from https://chessdb.cn/queryc_en/
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    lichess_cloud:
      enabled: false                      # Activate online moves from Lichess cloud eval.
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    online_egtb:
      enabled: false                      # Activate online endgame tablebases from Lichess.
      min_time: 10                        # Time the bot must have at least to use the online move.
      timeout: 3                          # Time the server has to respond.
  offer_draw:
    enabled: true                         # Activate whether the bot should offer draw.
    score: 10                             # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
    consecutive_moves: 10                 # How many moves in a row the absolute value of the score has to be below the draw value
    min_game_length: 35                   # Earliest move in which draw is offered.
  resign:
    enabled: false                        # Activate whether the bot should resign games.
    score: -1000                          # If the score is less than or equal to this value, the bot resigns (in cp).
    consecutive_moves: 5                  # How many moves in a row the score has to be below the resign value.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 10                    # Increase if your bot flags games too often.
    Threads: 4                            # Max CPU threads the engine can use.
    Hash: 512                             # Max memory (in megabytes) the engine can allocate.
    SyzygyPath: "/engines/3-4-5"         # Path to your local syzygy endgame tablebases

  move_overhead_multiplier: 1.0             # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    
 challenge:                                # Incoming challenges. (Commenting allowed)
 concurrency: 1                          # Number of games to play simultaneously.
 min_increment: 0                        # Minimum amount of increment to accept a challenge.
 max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
 variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
 time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
    - classical
 bot_modes:                              # Game modes to accept against BOTs.
    - casual                              # Unrated games.
    - rated                               # Rated games
 human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games

 matchmaking:
  initial_time: 60                        # Initial time for matchmaking mode.
  increment: 1                            # Increment time for matchmaking mode.
  rated: true                             # Activate rated games in matchmaking mode.
  timeout: 20                             # Time until a challenge is canceled. 
# min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
# max_rating_diff: 300                    # Maximum rating distance to opponent. (Commenting allowed)

 books:                                    # Names of the opening books (to be used above in the polyglot section) and paths to the polyglot opening books.
 DefaultBook: "/engines/book1.bin"

**Comment by trial-boy-bots** [comment]
now,  it says Exception: Section `challenge` must be a dictionary with indented keys followed by colons.. even though everything is fine

**Comment by trial-boy-bots** [comment]
so , can i paste the config u edited?

**Comment by Torom** [comment]
The problem is the indentation in the `challenge` section. You have to keep it indented like it is in the default config:

```
challenge:                                # Incoming challenges. (Commenting allowed)
  concurrency: 1                          # Number of games to play simultaneously.
# min_increment: 0                        # Minimum amount of increment to accept a challenge.
# max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
#   - classical
  bot_modes:                              # Game modes to accept against BOTs.
#   - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games
```

Also your book configuration will fail after you fix the indentation. You have to declare the books in the `books` section like this:
```
 books:                                    # Names of the opening books (to be used above in the polyglot section) and paths to the polyglot opening books.
  book1.bin: "/engines/book1.bin"
  book2.bin: "/engines/book2.bin"
```

**Comment by trial-boy-bots** [comment]
ah , okay

**Comment by trial-boy-bots** [comment]
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "config.yml", line 53, column 1
  :( if i leave the space there it says it needs colon , if i dont , it says parse error because of the blocking :(

**Comment by Torom** [comment]
Can you post the config you now try to use?

**Comment by trial-boy-bots** [comment]
token: "lip_IXHEWLysBEtLJCjqA4kq"    # Lichess OAuth2 Token.
 url: "https://lichess.org/"  # Lichess base URL.

 engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing the engine. This can be an absolute path or one relative to lichess-bot/.
  name: "sf.exe"        # Binary name of the engine to use.
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.                       # Think on opponent's time.
  opening_books:
    enabled: true                      # Activate opening books.
    books:
      white:                              # List of names of books to use as white.
        - "book1.bin"
      black:                              # List of names of books to use as black.
        - "book2.bin"
      standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "book1.bin" 
#     chess960:                           # List of names of books to use for Chess960.
#       - "Chess960Book"
    selection: "weighted_random"          # Move selection is one of "weighted_random", "uniform_random" or "best_move".
  online_moves:
    chessdb:
      enabled: false                      # Activate online moves from https://chessdb.cn/queryc_en/
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    lichess_cloud:
      enabled: false                      # Activate online moves from Lichess cloud eval.
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    online_egtb:
      enabled: false                      # Activate online endgame tablebases from Lichess.
      min_time: 10                        # Time the bot must have at least to use the online move.
      timeout: 3                          # Time the server has to respond.
  offer_draw:
    enabled: true                         # Activate whether the bot should offer draw.
    score: 10                             # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
    consecutive_moves: 10                 # How many moves in a row the absolute value of the score has to be below the draw value
    min_game_length: 35                   # Earliest move in which draw is offered.
  resign:
    enabled: false                        # Activate whether the bot should resign games.
    score: -1000                          # If the score is less than or equal to this value, the bot resigns (in cp).
    consecutive_moves: 5                  # How many moves in a row the score has to be below the resign value.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 10                    # Increase if your bot flags games too often.
    Threads: 4                            # Max CPU threads the engine can use.
    Hash: 512                             # Max memory (in megabytes) the engine can allocate.
    SyzygyPath: "/engines/3-4-5"         # Path to your local syzygy endgame tablebases

  move_overhead_multiplier: 1.0             # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    
challenge:                                # Incoming challenges. (Commenting allowed)
  concurrency: 1                          # Number of games to play simultaneously.
# min_increment: 0                        # Minimum amount of increment to accept a challenge.
# max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
#   - classical
  bot_modes:                              # Game modes to accept against BOTs.
#   - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games
    
  books:                                    # Names of the opening books (to be used above in the polyglot section) and paths to the polyglot opening books.
  book1.bin: "/engines/book1.bin"
  book2.bin: "/engines/book2.bin"

**Comment by trial-boy-bots** [comment]
the same one which you sent a few minutes ago

**Comment by trial-boy-bots** [comment]
ah forgot to remove the token

**Comment by Torom** [comment]
It seems like you not used my default config as a starting point, because the `url` field is one that doesn't exist in my bot. I think it is the best for you, to take my default config. copy it to `config.yml` and make only the changes you want. Try to don't change the indentation. You just have to insert an whitespace where you delte an `#`.

**Comment by trial-boy-bots** [comment]
oh , my bad , one of my friends gave me the config to improve the bot

**Comment by Torom** [comment]
? Do you even use BotLi?

**Comment by trial-boy-bots** [comment]
yes

**Comment by trial-boy-bots** [comment]
lock_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config.yml", line 10, column 6
expected <block end>, but found '<block mapping start>'
  in "config.yml", line 14, column 7
 
default config , just edited the token and where books should be used and syzygy, still shows the error

**Comment by Torom** [comment]
Yes. Because you did something wrong in the `opening_books` section

**Comment by trial-boy-bots** [comment]
opening_books:
    enabled: true                        # Activate opening books.
    books:
     white:                              # List of names of books to use as white.
       - "book1.bin"
     black:                              # List of names of books to use as black.
       - "book2.bin"
     standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "book1.bin"

**Comment by trial-boy-bots** [comment]
raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config.yml", line 4, column 3
expected <block end>, but found '<block mapping start>'
  in "config.yml", line 47, column 4 
  here it comes again :(

**Comment by trial-boy-bots** [comment]
line 4 is the directoryone and 47 is syzygy

**Comment by Torom** [comment]
```
  opening_books:
    enabled: true                       # Activate opening books.
    books:
      white:                              # List of names of books to use as white.
        - "book1.bin"
      black:                              # List of names of books to use as black.
        - "book2.bin"
      standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "book1.bin" 
#     chess960:                           # List of names of books to use for Chess960.
#       - "Chess960Book"
    selection: "weighted_random"          # Move selection is one of "weighted_random", "uniform_random" or "best_move".
```

This should work.

**Comment by trial-boy-bots** [comment]
> ```
> raise ParserError("while parsing a block mapping", self.marks[-1],
> ```
> 
> yaml.parser.ParserError: while parsing a block mapping in "config.yml", line 4, column 3 expected , but found '' in "config.yml", line 47, column 4 here it comes again :(

**Comment by trial-boy-bots** [comment]
okay , its working right now but i had to remove book1 as it said book1.bin doesnt exist in engines folder

**Comment by Torom** [comment]
```
token: "XXXXXXXXXXXXXXXXXXXXXXXX"         # Lichess OAuth2 Token.

engine:                                   # Engine settings.
  dir: "./engines"                        # Directory containing the engine.
  name: "sf.exe"                      # Binary name of the engine to use.
  ponder: true                            # Think on opponent's time.
  opening_books:
    enabled: true                       # Activate opening books.
    books:
      white:                              # List of names of books to use as white.
        - "book1.bin"
      black:                              # List of names of books to use as black.
        - "book2.bin"
      standard:                           # List of names of books to use if there is no specific book for white, black or chess960.
        - "book1.bin" 
#     chess960:                           # List of names of books to use for Chess960.
#       - "Chess960Book"
    selection: "weighted_random"          # Move selection is one of "weighted_random", "uniform_random" or "best_move".
  online_moves:
    chessdb:
      enabled: false                      # Activate online moves from https://chessdb.cn/queryc_en/
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    lichess_cloud:
      enabled: false                      # Activate online moves from Lichess cloud eval.
      min_depth: 10                       # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
    online_egtb:
      enabled: false                      # Activate online endgame tablebases from Lichess.
      min_time: 10                        # Time the bot must have at least to use the online move.
      timeout: 3                          # Time the server has to respond.
  offer_draw:
    enabled: true                         # Activate whether the bot should offer draw.
    score: 10                             # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
    consecutive_moves: 10                 # How many moves in a row the absolute value of the score has to be below the draw value
    min_game_length: 35                   # Earliest move in which draw is offered.
  resign:
    enabled: false                        # Activate whether the bot should resign games.
    score: -1000                          # If the score is less than or equal to this value, the bot resigns (in cp).
    consecutive_moves: 5                  # How many moves in a row the score has to be below the resign value.
  uci_options:                            # Arbitrary UCI options passed to the engine. (Commenting allowed)
    Move Overhead: 10                    # Increase if your bot flags games too often.
    Threads: 4                            # Max CPU threads the engine can use.
    Hash: 512                             # Max memory (in megabytes) the engine can allocate.
    SyzygyPath: "/engines/3-4-5"         # Path to your local syzygy endgame tablebases

move_overhead_multiplier: 1.0             # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    
challenge:                                # Incoming challenges. (Commenting allowed)
  concurrency: 1                          # Number of games to play simultaneously.
# min_increment: 0                        # Minimum amount of increment to accept a challenge.
# max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:                          # Time controls to accept.
    - bullet
    - blitz
    - rapid
#   - classical
  bot_modes:                              # Game modes to accept against BOTs.
#   - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
    - rated                               # Rated games

matchmaking:
  initial_time: 60                        # Initial time for matchmaking mode.
  increment: 1                            # Increment time for matchmaking mode.
  rated: true                             # Activate rated games in matchmaking mode.
  timeout: 20                             # Time until a challenge is canceled. 
# min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
# max_rating_diff: 300                    # Maximum rating distance to opponent. (Commenting allowed)

books:                                    # Names of the opening books (to be used above in the polyglot section) and paths to the polyglot opening books.
  book1.bin: "/engines/book1.bin"
  book2.bin: "/engines/book2.bin"

```

Just copy and paste this. This should work.

**Comment by trial-boy-bots** [comment]
okay

**Comment by trial-boy-bots** [comment]
its working , thank you so much for your time

**Comment by Torom** [comment]
You are welcome.
