### ISSUE TITLE
Misunderstanding problem

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#53]
Hey @Torom,
In config.yml. default I don't understand this matchmaking config:

  min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
  max_rating_diff: 500                   # Maximum rating distance to opponent. (Commenting allowed)

At the moment my bot is 2655 rated so why starting matchmaking it said no bots in range ?
Can you tell me a bit more on this min max rating config 
Thank you

**Comment by Torom** [comment]
At first glance, I can't see any error in your configuration. The way you use `min_rating_diff` and `max_rating_diff` should work. Can you post the exact error message?

**Comment by FatFritz2** [comment]
Ye I started matchmaking mode and it can't find any in range bots for a while (5 minutes?)

**Comment by Torom** [comment]
If you start matchmaking and the bot does not find any opponents in the range, the bot exits with a `RuntimeError`, so it no longer tries to search for opponents. That's why I asked for the exact error message.

**Comment by FatFritz2** [comment]
Ok I will
