### ISSUE TITLE
New step

### ISSUE THREAD

**Issue by KingsHollyCross** [Torom/BotLi#57]
Torom can you try making the code compatible for cloudfare.com ?

**Comment by Torom** [comment]
I think you need to clarify your request. In which way compatible with cloudflare?

**Comment by KingsHollyCross** [comment]
can you make the bot run on cloudflare.com????

**Comment by Torom** [comment]
I'm not going to guess which Cloudflare product you mean. Nor will I find out what it takes.

Have you tried if BotLi works there, if it does not, what were the problems?

In general, you should read this and try to follow it: https://lichess.org/@/thibault/blog/how-to-ask-technical-questions/1HSthDSX
