### ISSUE TITLE
Something unclear

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#61]
Idk what is this when the bot is in book move 
Book: 16... Re8 100 % or sometime it is 25% 50% i have no idea :C Please help what is that percentage for
And what is this "TB" ?  Hash: 2.2 % TB: 34.1 k
Also why the hash is not 100 % pls help idk

**Comment by Torom** [comment]
The percentages for moves from an opening book indicate how much weight that move has in the book. If the selection is set to `weighted_random`, it gives the probability of this move being played.

TB indicates the number of tablebase hits, in other words, how often the engine found a position in the endgame tablebase.

The hash fills up more and more in the process of a search. Depending on the available hash size and the performance of the CPU, it takes different amounts of time until the hash is filled. It is not the goal to fill the hash to 100%.

**Comment by FatFritz2** [comment]
Is there a way to enable TB in my bot's config and thanks ?

**Comment by Torom** [comment]
If you use BotLi in the cloud, there is no practical way to use local syzygy. But you can activate online egtb from lichess.

**Comment by FatFritz2** [comment]
No I am using my real CPU rn

**Comment by Torom** [comment]
You can download the syzygy endgame tablebases. They must be stored on an SSD. Then you can activate them in BotLi in the config under `syzygy`.
More information about syzygy: https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete

**Comment by FatFritz2** [comment]
Got it thanks :D
