### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#63]
I am stucked for a few days rn:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 35, in run
    if event['type'] == 'gameFull':
KeyError: 'type'

**Comment by Torom** [comment]
You would really make it easier for me to help you if you gave me more information than just an error message.

Under what circumstances does the error occur? Does this error always occur or only occasionally? Can you reproduce the error?

**Comment by FatFritz2** [comment]
> You would really make it easier for me to help you if you gave me more information than just an error message.
> 
> Under what circumstances does the error occur? Does this error always occur or only occasionally? Can you reproduce the error?

I followed all the instructions but it starts BotLi but this happened when i tried to play a game:


______       _   _     _
| ___ \     | | | |   (_)
| |_/ / ___ | |_| |    _
| ___ \/ _ \| __| |   | |
| |_/ / (_) | |_| |___| |
\____/ \___/ \__\_____/_|

Handling challenges ...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 35, in run
    if event['type'] == 'gameFull':
KeyError: 'type'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 35, in run
    if event['type'] == 'gameFull':
KeyError: 'type'

**Comment by Torom** [comment]
Ok. Can you add a `print(event)` to line 34 of `game.py`? And then please post the output when the error occurs, thanks.
Lines 32 to 35 should look like this:

```python
while True:
    event = self.game_queue.get()
    print(event)
        if event['type'] == 'gameFull':
```

**Comment by FatFritz2** [comment]
In the cmd console here it looks when i tried to add print(event):

Handling challenges ...
{'error': 'Missing scope'}
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\olymp\Downloads\BotLi-main\game.py", line 35, in run
    if event['type'] == 'gameFull':
KeyError: 'type

**Comment by Torom** [comment]
I would guess your used token does not have the necessary `bot:play` scope. But interesting, I should check that at startup.

**Comment by FatFritz2** [comment]
> I would guess your used token does not have the necessary `bot:play` scope. But interesting, I should check that at startup.

I will try to regen my token :D

**Comment by FatFritz2** [comment]
> > I would guess your used token does not have the necessary `bot:play` scope. But interesting, I should check that at startup.
> 
> I will try to regen my token :D

tried but doesnt work :C

**Comment by Torom** [comment]
Can you paste your token into this script and run it and then post the output. Please also remove your token from the output before you post it.

```python
import requests

response = requests.post('https://lichess.org/api/token/test', data='INSERT TOKEN HERE')
print(response.json())
```

**Comment by FatFritz2** [comment]
how to run this

**Comment by FatFritz2** [comment]
{MY_TOKEN': {'userId': 'torbot', 'scopes': 'challenge:read,challenge:write', 'expires': None}}

**Comment by Torom** [comment]
As I said. Your token is missing the bot:play scope. You can create such a token by following this link: https://lichess.org/account/oauth/token/create?scopes%5B%5D=bot:play&description=BotLi

**Comment by FatFritz2** [comment]
A thing is when i tried ur link, when done it just said like this 
![image](https://user-images.githubusercontent.com/107122824/203595197-17c8fadf-13e8-4a09-9a31-b78b91acf5dc.png)

**Comment by Torom** [comment]
So? If you test this token with `scope_test.py`? What comes out?

**Comment by FatFritz2** [comment]
no Bot:play scope enabled

**Comment by Torom** [comment]
I don't know what the problem is. At least it is not a BotLi error. I will introduce a check of the token at startup so that such errors get a clear error message.

**Comment by FatFritz2** [comment]
Ok I will have to ask Lichess for now :(

**Comment by FatFritz2** [comment]
It's Lichess's end fault not ours

**Comment by Torom** [comment]
If you test with the current version of BotLi you should at least get a clear error message.

**Comment by Torom** [comment]
I was just able to create a token with the `bot:play` scope, the problem seems to be fixed.

**Comment by FatFritz2** [comment]
> 

U r right
