### ISSUE TITLE
MUST be a matchmaking error ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#73]
This is just a real error. Every time tring to use matchmaking, I  got this not once only so it must be a bug:
![image](https://user-images.githubusercontent.com/107122824/209150590-e18b59cc-b481-4248-95a2-5b7b3eee6a21.png)

**Comment by FatFritz2** [comment]
Moreover, I did not change any other .py files as you said, I am not editting anything just note

**Comment by Torom** [comment]
Please don't just delete the issue template every time but use it! Especially I need the exact steps to reproduce the error and the used config.

**Comment by Torom** [comment]
I guess I found the error without your feedback. It only occurred when the user had configured an invalid time control. This is handled correctly since cc627f8.
