### ISSUE TITLE
Python 3.9 (or back) support

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#76]
Hi, in the requirements section, you said: Only Python 3.10 or later is supported.
But one thing is that can you add support for Python 3.9 (at least) if possible ?

**Comment by Torom** [comment]
I have no interest in supporting older Python versions than 3.10.
It should be easy to install a suitable Python version (I recommend Python 3.11). For example with [pyenv](https://github.com/pyenv/pyenv).
