### ISSUE TITLE
Adding back heroku cloud feature

### ISSUE THREAD

**Issue by KingsHollyCross** [Torom/BotLi#77]
Torom I have been working on this for last 3 months and I got some suggestions from FatFritz2 as well. If you add those features back, we can run that using railway.app 
If you can add that feature, I think it will bring all the cloud bots back online.

**Comment by Torom** [comment]
Can you maybe explain what feature you are talking about?

**Comment by FatFritz2** [comment]
You can go back to this commit in order to run on railway.app
7183f9f1f8166110af1baba47f2d34dbf2847c52
