### ISSUE TITLE
Adding Lichess Evaluation for chess960 

### ISSUE THREAD

**Issue by QANs12** [Torom/BotLi#81]
This is something that is needed for your Botli. When stockfish play with its normal evaluation on a normal/ low computer, the opening gets worse and much worse during the midgame.

The solution for this I thought was adding lichess cloud eval to chess960 just like for standard games.

If this becomes successful, I think it can help the stockfish to play in a stronger manner.

**Comment by Torom** [comment]
Have you checked if Lichess really has a cloud evaluation for the following positions? It is usually the case with 960 that Lichess only has a cloud evaluation for the start positions.

**Comment by QANs12** [comment]
here https://lichess.org/api#tag/Analysis/operation/apiCloudEval
I think We can get cloud eval for any variant

**Comment by Torom** [comment]
That is not the point. BotLi uses this endpoint for cloud evaluation. I just assume that Lichess has no evaluation for the position in question. Please post the link to a game where BotLi plays only the first move from the cloud.

**Comment by QANs12** [comment]
I think this is the game https://lichess.org/FleDFbVu/black#5

**Comment by QANs12** [comment]
> here https://lichess.org/api#tag/Analysis/operation/apiCloudEval I think We can get cloud eval for any variant

I went through this as well it shows variants are available which means chess960 too.
Can you tell the py file where cloud eval thing is there?

**Comment by Torom** [comment]
> I think this is the game https://lichess.org/FleDFbVu/black#5

Okay, these are the cloud evaluations for this game:

start position:
```json
{"fen":"nnbrkbqr/pppppppp/8/8/8/8/PPPPPPPP/NNBRKBQR w KQkq - 0 1","knodes":27674,"depth":26,"pvs":[{"moves":"f2f3 a8b6 d2d4 f7f6 a1b3 g8f7 e2e4 d7d5 b1c3 d5e4","cp":67}]}
```
after move `1. f3`:
```json
{"fen":"nnbrkbqr/pppppppp/8/8/8/5P2/PPPPP1PP/NNBRKBQR b KQkq - 0 1","knodes":909,"depth":21,"pvs":[{"moves":"a8b6 d2d4 f7f5 b1c3 g8f7 a1b3 d7d6 e2e4 e7e5 d4e5","cp":62}]}
```

after move `1... Nb6`:
```json
{"error":"Not found"}
```

So as you can see, it's not because of BotLi that no more moves are played from the cloud. The cloud simply has no more moves in further positions.
