### ISSUE TITLE
Dockerfile error 

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#84]
Hi Torom 
When I was trying to rebuild the Dockerfile to a cloud hosting, I installed all the requirements but it occurs like
```
 File "/workspaces/OldBotLi/user_interface.py", line 213, in <module>
    ui = UserInterface()
  File "/workspaces/OldBotLi/user_interface.py", line 24, in __init__
    self.config = load_config()
  File "/workspaces/OldBotLi/config.py", line 53, in load_config
    raise Exception(
Exception: The engine "./engines/stockfish" doesnt have execute (x) permission. Try: chmod +x ./engines/stockfish
```

Also it is using ubuntu of course  (I am using Github Codespace to do this)

**Comment by Torom** [comment]
I added an up-to-date Dockerfile to the `main` branch in fb083c8.

**Comment by Torom** [comment]
Have you tried the new Dockerfile? And if you want me to help, please post the Dockerfile you used.

**Comment by FatFritz2** [comment]
Oh let me see...

**Comment by FatFritz2** [comment]
I guess github codespace doesn't compatible with BotLi so I'd just close this issue now
