### ISSUE TITLE
Is there any errors here ?

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#85]
Hi, I am running BotLi on the web and occurred this:

```
Apr 18 07:56:09 PM  Traceback (most recent call last):
Apr 18 07:56:09 PM    File "//user_interface.py", line 277, in <module>
Apr 18 07:56:09 PM      ui.main()
Apr 18 07:56:09 PM    File "//user_interface.py", line 67, in main
Apr 18 07:56:09 PM      command = input().split()
Apr 18 07:56:09 PM  EOFError: EOF when reading a line
```

I don't know what happened here. Please help

**Comment by Torom** [comment]
If you run BotLi in an environment without input you should set the `--non_interactive` flag.

**Comment by Torom** [comment]
However, since da01d72 the `--non_interactive` flag is no longer needed, BotLi now detects itself if an interactive terminal is available.
