### ISSUE TITLE
Readd support for heroku

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#93]
Can you add heroku support in the actions/workflow again due to some people need it to run smoothly on heroku

![image](https://github.com/Torom/BotLi/assets/107122824/e8799d17-ac37-442b-a91b-074f8bcf2864)

**Comment by Torom** [comment]
The engine crashed. I can't tell you more with the given information.
To isolate the issue you should try to run the engine without BotLi. It is usually no BotLi issue when the engine doesn't work.

**Comment by Torom** [comment]
No
