### ISSUE TITLE
Matchmaking

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#98]
Is there any way so that my bot will challenge another specific bot more times than other bots. For example, out of 10 games, it will challenge a specific bot 7 times but random bots 3 times. I want to do this because I want my two bots @EmptikBot and @EmptikVariantsBot to play against each other more often

**Comment by Torom** [comment]
No, there is no such function. But you can create any number of challenges manually: `create COUNT USERNAME [INITIAL_TIME] [INCREMENT] [RATED] [VARIANT]`

**Comment by EmptikBest** [comment]
So will all of them be sent at once?

**Comment by EmptikBest** [comment]
Also, is there any way for the bot to send a rematch automatically after a game is finished?

**Comment by Torom** [comment]
> So will all of them be sent at once?

Of course not, they are sent one after the other.

> Also, is there any way for the bot to send a rematch automatically after a game is finished?

No.

**Comment by EmptikBest** [comment]
Also, what do I put in place of [RATED]? I tried saying 'Rated' and 'Yes' but they both sent causal

**Comment by Torom** [comment]
> Sorry for all the questions, but I mean like will the other challenge be sent after the first game has ended? Won't it just expire?

The next challenge is send directly after the game before ends.

> Also, what do I put in place of [RATED]? I tried saying 'Rated' and 'Yes' but they both sent causal

`true` / `false`

**Comment by EmptikBest** [comment]
Thank you very much
