### ISSUE TITLE
Challenging

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#99]
I ran `create 20 EmptikVariantsBot 60 0 true standard` and left the computer for one hour, when I came back it hadn't finished even close to 20 games and was playing some other games. Any idea why? (Check @EmptikBot's games on lichess that have played against @EmptikVariantsBot)

**Comment by Torom** [comment]
If someone else challenges EmptikVariantsBot, it will accept this challenge. The challenging BotLi will stop the created challenges after a challenge that timed out and returns to normal operation.

Note that the 20 or whatever number you choose stands for game pairs. So 20 games as white and 20 as black.

**Comment by EmptikBest** [comment]
How do I disable this for both EmptikBot and EmptikVariantsBot? I want them to challenge each other for a few games, then return back to BotLi default matchmaking mode

**Comment by Torom** [comment]
This is not possible. The challenged bot will handle the challenges as first comes first servers. So there is no way to prioritize your own challenges over others.
The challenging bot will send the challenges and will not accept challenges while challenging.

**Comment by EmptikBest** [comment]
Thanks
